version: 0.1
keywords: "HTML, Javascript, Visual Experience"
title: "Distortion #1"
description: "Connection #1 is a part of visual experiences I had recently. It works with dots and straight line to create a illusion based on user interactions..."
url: "http://behrooz-tahanzadeh.github.io/distortion-1/"
date: "December 2015"
googleAnalyticsCode: "UA-40560087-5"
